# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_chat_gpt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12rpc_chat_gpt.proto\x12\x07\x63hatgpt\"/\n\x0e\x43hatGptRequest\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x0c\x43hatGptReply\x12\x10\n\x08response\x18\x01 \x01(\tBRZPgithub.com/onepiece010938/go-line-message-analyzer/internal/adapter/grpc/chatgptb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_chat_gpt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZPgithub.com/onepiece010938/go-line-message-analyzer/internal/adapter/grpc/chatgpt'
  _CHATGPTREQUEST._serialized_start=31
  _CHATGPTREQUEST._serialized_end=78
  _CHATGPTREPLY._serialized_start=80
  _CHATGPTREPLY._serialized_end=112
# @@protoc_insertion_point(module_scope)
