# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_open_ai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rpc_chat_gpt_pb2 as rpc__chat__gpt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15service_open_ai.proto\x12\x07\x63hatgpt\x1a\x12rpc_chat_gpt.proto2C\n\x06OpenAi\x12\x39\n\x07\x43hatGpt\x12\x17.chatgpt.ChatGptRequest\x1a\x15.chatgpt.ChatGptReplyBRZPgithub.com/onepiece010938/go-line-message-analyzer/internal/adapter/grpc/chatgptb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_open_ai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZPgithub.com/onepiece010938/go-line-message-analyzer/internal/adapter/grpc/chatgpt'
  _OPENAI._serialized_start=54
  _OPENAI._serialized_end=121
# @@protoc_insertion_point(module_scope)
