# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc_chat_gpt_pb2 as rpc__chat__gpt__pb2


class OpenAiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatGpt = channel.unary_unary(
                '/chatgpt.OpenAi/ChatGpt',
                request_serializer=rpc__chat__gpt__pb2.ChatGptRequest.SerializeToString,
                response_deserializer=rpc__chat__gpt__pb2.ChatGptReply.FromString,
                )


class OpenAiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatGpt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatGpt': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatGpt,
                    request_deserializer=rpc__chat__gpt__pb2.ChatGptRequest.FromString,
                    response_serializer=rpc__chat__gpt__pb2.ChatGptReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatgpt.OpenAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpenAi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatGpt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatgpt.OpenAi/ChatGpt',
            rpc__chat__gpt__pb2.ChatGptRequest.SerializeToString,
            rpc__chat__gpt__pb2.ChatGptReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
